name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the main branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version:
          - 'devel'
          - '4.15'
          - '4.14'
          - '4.13'
          - '4.12'
        pkgs-to-clone: 
          - |
            gap-packages/datastructures@devel
            gap-packages/NautyTracesInterface@devel
            digraphs/digraphs@devel

    steps:
      - name: "Checkout package repository"
        uses: actions/checkout@v6
      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: "Setup GAP"
        uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}
      - name: "Clone packages"
        uses: gap-actions/install-pkg@v1
        with:
          packages: ${{ matrix.pkgs-to-clone }}
      - name: "Build 'typeset' package"
        uses: gap-actions/build-pkg@v3
        with:
          build-suggested-pkgs: 'recursive' # Also build packages suggested by digraphs
      - name: "Run 'typeset' package tests"
        uses: gap-actions/run-pkg-tests@v4
      - name: "Run 'typeset' package tests (with only needed packages loaded)"
        uses: gap-actions/run-pkg-tests@v4
        with:
          mode: onlyneeded
      - name: "Process test coverage"
        uses: gap-actions/process-coverage@v3
      - name: "Publish code coverage"
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
